#!/bin/bash

file_path="./Bonkulator/version_num.h"
file_path2="./Bonkulator/is_release.h"

echo "This will set the Bonkulator software release number in $file_path"

if [ -n "$BONK_RELEASE_NUM" ]; then
    echo "The current release number is: $BONK_RELEASE_NUM"
fi

read -p "What's the NEW software release number? " release_num

read -p "That's $release_num, eh? (y/n) " ans

if [ "$ans" != "y" ]; then
    echo "Goodbye!"
    exit
fi

export BONK_RELEASE_NUM=$release_num

echo "// *** Warning! *** Do not edit this file. Use release.sh instead." > $file_path
echo "#ifndef VERSION_NUM_h" >> $file_path
echo "#define VERSION_NUM_h" >> $file_path
echo "" >> $file_path
echo "#define VERSION_NUM \"v$release_num\"" >> $file_path
echo "" >> $file_path
echo "#endif" >> $file_path

echo "// *** Warning! *** Do not edit this file. release.sh sets value." > $file_path2
echo "#ifndef IS_RELEASE_h" >> $file_path2
echo "#define IS_RELEASE_h" >> $file_path2
echo "" >> $file_path2
echo "#define IS_RELEASE true" >> $file_path2
echo "" >> $file_path2
echo "#endif" >> $file_path2

./make.sh

echo "// *** Warning! *** Do not edit this file. release.sh sets value." > $file_path2
echo "#ifndef IS_RELEASE_h" >> $file_path2
echo "#define IS_RELEASE_h" >> $file_path2
echo "" >> $file_path2
echo "#define IS_RELEASE false" >> $file_path2
echo "" >> $file_path2
echo "#endif" >> $file_path2

cp ./out/Bonkulator.ino.bin updater
cp ./out/Bonkulator.ino.elf updater
cp Blink.ino.elf.uf2 updater
echo $release_num > updater/release.txt

# Create a zip file using the zip command
zip -r ./releases/bonkulator_updater_$release_num.zip updater -x updater.sh

# Create a tar archive using the tar command
tar -cf archive.tar --exclude=updater/update.bat updater

# Compress the tar archive into .gz format using the gzip command
gzip ./archive.tar

# Rename the .tar.gz file to .tar.zip so that it can be uploaded to Worddpress site
mv ./archive.tar.gz ./releases/bonkulator_updater_$release_num.tar.zip

echo "Goodbye!"