M48
; DRILL file {KiCad (6.0.1)} date Fri Oct 28 09:23:40 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-28T09:23:40-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1457
%
G90
G05
T1
X2.1654Y-2.126
X2.1654Y-6.1811
T2
X2.1654Y-2.8346
X2.1654Y-3.2283
X2.1654Y-3.622
X2.1654Y-4.0157
X2.1654Y-5.5591
T3
X2.1654Y-2.5049
T0
M30
